import { Controller, Post, Get, Body, Param, UseGuards, ParseUUIDPipe } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiBearerAuth } from '@nestjs/swagger';
import { Throttle } from '@nestjs/throttler';
import { Role } from '@prisma/client';
import { NotesService } from './notes/notes.service';
import { QuizService } from './quiz/quiz.service';
import { GradingService } from './grading/grading.service';
import { ChatService } from './chat/chat.service';
import {
  GenerateNotesDto, GenerateQuizDto, GradeSubmissionDto, ChatMessageDto, GenerateAssignmentDto,
  GenerateCourseDto,
} from './dto/ai.dto';
import { AiCourseService } from './course/ai-course.service';
import { JwtAuthGuard } from '../common/guards/jwt-auth.guard';
import { RolesGuard } from '../common/guards/roles.guard';
import { Roles } from '../common/decorators/roles.decorator';
import { CurrentUser } from '../common/decorators/current-user.decorator';

@ApiTags('ai')
@ApiBearerAuth()
@UseGuards(JwtAuthGuard, RolesGuard)
@Controller('ai')
export class AiController {
  constructor(
    private readonly notesService: NotesService,
    private readonly quizService: QuizService,
    private readonly gradingService: GradingService,
    private readonly chatService: ChatService,
    private readonly aiCourseService: AiCourseService,
  ) {}

  // ─── Notes ──────────────────────────────────────────────────────────────────

  @Post('notes/generate')
  @Roles(Role.INSTRUCTOR, Role.ADMIN)
  @Throttle({ medium: { limit: 5, ttl: 60000 } })
  @ApiOperation({ summary: 'Generate academic notes (Instructor/Admin)' })
  generateNotes(
    @Body() dto: GenerateNotesDto,
    @CurrentUser() user: { id: string },
  ) {
    return this.notesService.generateNotes(dto, user.id);
  }

  @Get('notes/:id')
  @ApiOperation({ summary: 'Get generated notes by ID' })
  getNotes(@Param('id', ParseUUIDPipe) id: string) {
    return this.notesService.findById(id);
  }

  @Get('notes')
  @Roles(Role.INSTRUCTOR, Role.ADMIN)
  @ApiOperation({ summary: 'Get all notes generated by current instructor' })
  getMyNotes(@CurrentUser() user: { id: string }) {
    return this.notesService.findByInstructor(user.id);
  }

  // ─── Quiz ────────────────────────────────────────────────────────────────────

  @Post('quiz/generate')
  @Roles(Role.INSTRUCTOR, Role.ADMIN)
  @Throttle({ medium: { limit: 5, ttl: 60000 } })
  @ApiOperation({ summary: 'Generate a quiz from lesson content (Instructor/Admin)' })
  generateQuiz(
    @Body() dto: GenerateQuizDto,
    @CurrentUser() user: { id: string },
  ) {
    return this.quizService.generateQuiz(dto, user.id);
  }

  @Get('quiz/:id')
  @ApiOperation({ summary: 'Get quiz by ID' })
  getQuiz(@Param('id', ParseUUIDPipe) id: string) {
    return this.quizService.findById(id);
  }

  // ─── Grading ─────────────────────────────────────────────────────────────────

  @Post('grade')
  @Throttle({ medium: { limit: 10, ttl: 60000 } })
  @ApiOperation({ summary: 'Grade a student submission (AI-powered)' })
  gradeSubmission(@Body() dto: GradeSubmissionDto) {
    return this.gradingService.gradeSubmission(dto);
  }

  // ─── Chat ────────────────────────────────────────────────────────────────────

  @Post('chat')
  @Throttle({ medium: { limit: 20, ttl: 60000 } })
  @ApiOperation({ summary: 'Send message to AI tutor' })
  chat(
    @Body() dto: ChatMessageDto,
    @CurrentUser() user: { id: string },
  ) {
    return this.chatService.sendMessage(dto, user.id);
  }

  @Get('chat/sessions')
  @ApiOperation({ summary: 'Get all chat sessions for current user' })
  getChatSessions(@CurrentUser() user: { id: string }) {
    return this.chatService.getSessions(user.id);
  }

  @Get('chat/sessions/:sessionId')
  @ApiOperation({ summary: 'Get a specific chat session with messages' })
  getChatSession(
    @Param('sessionId', ParseUUIDPipe) sessionId: string,
    @CurrentUser() user: { id: string },
  ) {
    return this.chatService.getSession(sessionId, user.id);
  }

  // ─── Course ─────────────────────────────────────────────────────────────────

  @Post('course/generate')
  @Roles(Role.INSTRUCTOR, Role.ADMIN)
  @Throttle({ medium: { limit: 5, ttl: 60000 } })
  @ApiOperation({ summary: 'Generate course metadata (Instructor/Admin)' })
  generateCourseMetadata(@Body() dto: GenerateCourseDto) {
    return this.aiCourseService.generateMetadata(dto);
  }
}
